// https://projecteuler.net/problem=12
/* The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 *  */
// The number of divisors can be found using the formula
// (a+1)(b+1)(c+1)....
// Where a, b, c .... are the value of the exponent after performing prime
// factorization. For example 24 - 2^3 * 3^1 Has (3+1)(1+1) = 8 factors
//
// Algorithm
// ==========
// 1. Get a triangle number
// 2. Find the prime factorization of the number(I am using sieve of
// Eratosthenes) to find the primes here.
// 3. Find the number of divisors of the number by using the formula
// This program also performs and displays the prime factorization of the number
// NOTE: This program only works to numbers upto 10^12
// If you want to increase the limit, increase MAX_N and change the type of int_ and PRINTF_FORMAT
#include <math.h>
#include <stdio.h>
#define MAX_N 1000000  // 1 million
#define PRINTF_FORMAT "%d"
typedef int int_;
char soe[MAX_N] = {0};

void populateSOE()
{
    soe[0] = 1;
    soe[1] = 1;
    // Finds all prime less than MAX_N using Sieve of Eratosthenes algorithm
    // A value of 0 indicates that index is a prime, while a vaule of 1
    // indicates that the index is non-prime.
    int_ i = 2;
    while (i <= sqrt(MAX_N)) {
        for (int_ j = i * i; j < MAX_N; j += i) {
            soe[j] = 1;
        }
        while (soe[++i])
            ;
    }
}

int_ getTriangleNumber(int_ n) { return n * (n + 1) / 2; }

void printPrimeFactoriazation(int_ n)
{
    int_ count = 0;
    for (int_ k = 2; k <= sqrt(n);) {
        count = 0;
        while (n % k == 0) {
            n = n / k;
            count++;
        }
        if (count) printf(PRINTF_FORMAT "^" PRINTF_FORMAT " ", k, count);
        while (soe[++k])
            ;
    }
    if (soe[n] == 0) printf(PRINTF_FORMAT "^1 ", n);
    printf("\n");
}

int_ getNumberOfFactors(int_ n)
{
    int_ count = 0;
    // The formula for finding number of divisors is (p1 + 1)(p1 + 1) .... (pr
    // +1)
    int_ numFactors = 1;
    for (int_ k = 2; k <= sqrt(n);) {
        count = 0;
        while (n % k == 0) {
            n = n / k;
            count++;
        }
        numFactors *= (count + 1);
        // if (count) printf("%ld^%ld ", k, count);
        while (soe[++k])
            ;
    }
    // if (soe[n] == 0) printf("%ld^1 ", n);
    if (soe[n] == 0) numFactors *= (1 + 1);

    // printf("\n");
    return numFactors;
}

int main()
{
    populateSOE();
    int_ var = 1;
    /*
    while (1) {
        if (!scanf("%d", &var)) {
            break;
        }
        printf("%ld\n", getNumberOfFactors(var));
    }
    */
    while (getNumberOfFactors(getTriangleNumber(var)) <= 500) {
        // printf("%llu (%llu) - %llu\n", var, getTriangleNumber(var),
        // getNumberOfFactors(getTriangleNumber(var)));
        var++;
    }

    printf("The " PRINTF_FORMAT " th triangle number has:\n", var);
    printf(PRINTF_FORMAT " factors\n",
           getNumberOfFactors(getTriangleNumber(var)));
    printf("and has a value of " PRINTF_FORMAT "\n", getTriangleNumber(var));
    printf("Prime factorization: ");
    printPrimeFactoriazation(getTriangleNumber(var));
}
// NOTES:
// 23*23*17 = 8993, on this input, the program also outputs a 1^1 at the end.
// OUTPUT
/*
The 12375 th triangle number has:
576 factors
and has a value of 76576500
Prime factoriaztion: 2^2 3^2 5^3 7^1 11^1 13^1 17^1
*/
