/* https://projecteuler.net/problem=2 */
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
#include <stdio.h>

/* Naive solution */
int fib(int n)
{
    // a is the first term of the pair and b is the second term of the pair.
    int a = 1, b = 2, tmp;
    // For the second term 2
    int sum = 2;
    while ((a + b) < n) {
        tmp = a;
        a = b;
        b = tmp + b;
        sum += (b % 2 == 0) ? b : 0;
    }
    return sum;
}

/* Pattern based solution */
// The even numbers of fibonacci series, 2, 8, 34, 144 ...
// Follow the pattern
// 8 = 4 * 2 + 0
// 34 = 4 * 8 + 2
// 144 = 4 * 34 + 8
// And so on
// The next number of the series is 4 times the previous number + the second previous number.

int evenFib(int n)
{
    int prevI = 0, sum = 0, tmp;
    for (int i = 2; i < n;) {
        tmp = i;
        sum += i;
        i = 4 * i + prevI;
        prevI = tmp;
    }
    return sum;
}
int main()
{
    printf("%d\n", fib(4e6));
    printf("%d\n", evenFib(4e6));
}
